# Generated by Django 5.2.4 on 2025-07-23 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('years', models.DecimalField(decimal_places=1, max_digits=4)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='users.seekerprofile')),
            ],
        ),
    ]
