# Generated by Django 5.2.4 on 2025-07-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_education_passing_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='passing_years',
            new_name='passing_year',
        ),
    ]
