# Generated by Django 5.2.4 on 2025-07-23 08:27

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Job Description')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=250)),
                ('industry', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('education', models.CharField(max_length=500)),
                ('skills', models.CharField(max_length=250)),
                ('min_salary_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_salary_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-Time'), ('Part-time', 'Part-Time'), ('Internship', 'Internship')], default='Full-Time', max_length=20)),
                ('sub_type', models.CharField(choices=[('In-Office', 'In-Office'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='In-Office', max_length=20)),
                ('openings', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=250)),
                ('min_experience', models.IntegerField(blank=True, null=True)),
                ('max_experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
