# Generated by Django 5.2.3 on 2025-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('internship', 'Internship')], default='fulltime', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary_lpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary_lpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ManyToManyField(blank=True, to='jobs.location'),
        ),
    ]
