# Generated by Django 5.2.3 on 2025-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
