# Generated by Django 5.2.4 on 2025-07-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-Time'), ('Part-time', 'Part-Time'), ('Internship', 'Internship')], default='fulltime', max_length=20),
        ),
    ]
