# Generated by Django 5.2.4 on 2025-07-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
