# Generated by Django 5.2.4 on 2025-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='openings',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sub_type',
            field=models.CharField(choices=[('In-Office', 'In-Office'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='In-Office', max_length=20),
        ),
    ]
