# Generated by Django 5.2.4 on 2025-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_openings_job_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='openings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
