# Generated by Django 5.2.4 on 2025-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_openings'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
