# Generated by Django 5.2.4 on 2025-07-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_max_experience_job_min_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-Time'), ('Part-time', 'Part-Time'), ('Internship', 'Internship')], default='Full-Time', max_length=20),
        ),
    ]
